name: Generate Dataset (Manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: pip install --upgrade pip

      - name: 🔧 Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: ▶️ Run dataset script (push ligue par ligue)
        run: |
          python scripts/dataset.py
        env:
          GIT_PUSH: "true"