name: Generate Dataset (Manual)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: pip install --upgrade pip

      - name: 🔧 Configure git
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

      - name: ▶️ Run dataset script
        run: python scripts/dataset.py

      - name: 💾 Commit and push dataset
        run: |
          git add dataset_ml.json
          git diff --cached --quiet && echo "Rien à committer" && exit 0
          git commit -m "🤖 Update dataset_ml.json [$(date +'%Y-%m-%d %H:%M')]"
          git push