name: Generate Dataset (Manual)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🐍 Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 📦 Install dependencies
        run: |
          pip install --upgrade pip

      - name: ▶️ Run dataset script
        run: |
          python scripts/dataset.py

      - name: 💾 Commit & push dataset
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add dataset_ml.json

          git diff --cached --quiet || git commit -m "🤖 Manual dataset update"
          git push