name: Generate Dataset

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run dataset script
      run: python t.py

    - name: Upload dataset artifact
      uses: actions/upload-artifact@v4  # 🔹 mise à jour ici
      with:
        name: dataset-expert-full
        path: dataset-expert-full.json